/* 10份冲刺资料：题面、作答、原书批注分开；原 PNG 只在浏览器按坐标裁切。 */
window.PRACTICE = (() => {
  'use strict';
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let index, currentEdit, observer, listIds=null;const books=new Map(),pending=new Map(),listStates=new Map();
  const $=s=>document.querySelector(s), clone=o=>JSON.parse(JSON.stringify(o));
  const book=id=>index.books.find(b=>b.id===id), src=(id,n)=>index.sourceBase+'img/'+id+'/'+String(n).padStart(3,'0')+'.png';
  async function load(){if(!index){const r=await fetch('data/practice-index.json?v=112');if(!r.ok)throw Error('冲刺资料目录加载失败');index=await r.json();}return index;}
  async function needBook(id,S){await load();if(!book(id))throw Error('资料不存在');if(!books.has(id)){
    if(!pending.has(id))pending.set(id,(async()=>{const r=await fetch('data/practice/'+id+'.json?v=112');if(!r.ok)throw Error('题库加载失败，请重试');const d=await r.json();books.set(id,d);return d;})().finally(()=>pending.delete(id)));
    await pending.get(id);
  }const d=books.get(id);d.questions.forEach(q=>S.byId[q.id]=q);return d;}
  async function ensureQuestion(id,S){await load();const b=index.books.find(b=>id.startsWith('pr-'+b.id+'-'));if(b)await needBook(b.id,S);}
  function pool(id){const q=[...books.values()].flatMap(b=>b.questions).find(q=>q.id===id);if(!q)return [];const all=books.get(q.bookId).questions;return listIds&&listIds.includes(id)?listIds.map(k=>all.find(q=>q.id===k)).filter(Boolean):all;}
  function leave(){if(currentEdit)ZS.endEdit('edit',currentEdit);currentEdit=null;if(observer){observer.disconnect();observer=null;}}
  function reset(id){const e=ZS.data.edit[id];if(e){delete e.practiceMatch;delete e.practiceText;e.ts=Date.now();ZS.save();}}
  function fitBar(bar){const top=document.getElementById('topbar');const fit=()=>{if(bar.isConnected)bar.style.top=((top?top.getBoundingClientRect().height:80)+6)+'px';};fit();if(window.ResizeObserver){observer=new ResizeObserver(fit);if(top)observer.observe(top);}}
  function pdf(id,n,label='打开原 PDF'){return '<a class="btn tiny" target="_blank" rel="noopener" href="'+book(id).url+'#page='+n+'&zoom=page-width">'+esc(label)+'</a>';}
  function sourceHtml(q,refs,area='a-img-'){
    return refs.map((r,i)=>{const p=book(q.bookId).pageSizes[r.page-1],b=r.b,ar=area+i;
      return '<div class="tiny muted">'+esc(book(q.bookId).title)+' · PDF P'+r.page+'</div><div class="pgwrap p-clip" style="aspect-ratio:'+b[2]+'/'+b[3]+'" data-id="'+q.id+'" data-tgt="a-img" data-anno="'+q.id+'|'+ar+'"><img loading="lazy" src="'+src(q.bookId,r.page)+'" style="width:'+p.width/b[2]*100+'%;left:'+(-b[0]/b[2]*100)+'%;top:'+(-b[1]/b[3]*100)+'%;" alt="原文件对应片段" data-label="'+esc(book(q.bookId).title)+' P'+r.page+'" onload="ZS_ANNOSYNC()" onclick="ZS_ZOOM(this)"><button class="annobtn" onclick="ZS_ANNO(\''+q.id+'\',\''+ar+'\')">✍️</button></div><div class="acts"><button class="btn tiny" onclick="ZS_ZOOMSRC(\''+src(q.bookId,r.page)+'\')">放大完整原图</button>'+pdf(q.bookId,r.page)+'<button class="btn tiny" onclick="ZS_GO(\'sprint/practice/'+q.bookId+'/read/'+r.page+'\')">浏览笔记原页</button></div>';
    }).join('');
  }
  const questionPages=(q,which='key')=>sourceHtml(q,which==='key'?q.keyRefs:q.qRefs);
  const questionPdf=(q,which)=>Array.from(new Set((which==='key'?q.keyRefs:q.qRefs).map(r=>r.page))).map(n=>pdf(q.bookId,n,'打开资料对应原页')).join('');
  const badge=(q,c)=>(c.isWrongNow(q.id)?'❌ 错题 · ':'')+(c.flag(q.id,'star')?'★ 收藏 · ':'')+'已做 '+(c.P(q.id)?.tries||0)+' 次';
  async function render(route,c){
    c.showQNav(false);c.shell('<div class="empty">正在加载冲刺资料…</div>', true);
    try{
      await load();if(c.S.route!==route)return;const parts=route.split('/'),id=parts[2];
      if(!id){collection(c);return;}
      const d=await needBook(id,c.S);if(c.S.route!==route)return;
      if(parts[3]==='read')return reader(id,Number(parts[4])||1,c);
      list(id,c);
    }catch(e){if(c.S.route===route)c.shell('<div class="empty">'+esc(e.message)+'<div class="acts"><button class="btn" onclick="location.reload()">重新加载</button></div></div>');}
  }
  const shortTitle={
    'cf-upper':'乘风肖1000题笔记 · 上册','cf-lower':'乘风1000题笔记 · 下册',
    'leg-round':'腿姐 · 一轮选择合集','leg-marx':'腿姐 · 马原选择合集',
    'xu-marx':'徐涛 · 马原选择合集','xu-ethics':'徐涛 · 思修选择合集',
    'xu-history':'徐涛 · 史纲选择合集','history-second':'史纲 · 二刷选择合集',
    'ethics-match':'思修 · 连线题','xu-daily':'徐涛马原 · 每日任务合集'
  };
  function collection(c){
    const groups=[['notes','逐题笔记','先练选择题，提交后对照批注和原书。'],['matching','连线练习','连线、填序号两种方式，答案与记录共用。'],['daily','每日真题','按 DAY 练习真题，任务表在原页中浏览。']];
    c.shell('<div class="sprint-page"><a class="sprint-back" href="#/sprint">‹ 冲刺板块</a><div class="hero sprint-hero"><span class="sprint-eyebrow">题库与笔记</span><h1>选择题 / 笔记合集</h1><p>10 份资料 · '+index.total+' 道练习，按资料类型选择。</p></div>'+groups.map(([kind,title,desc])=>'<section class="p-collection-group"><div class="sprint-section-head"><h2>'+title+'</h2><span>'+index.books.filter(b=>b.kind===kind).length+' 份资料</span></div><p class="sprint-section-desc">'+desc+'</p><div class="p-book-grid">'+index.books.filter(b=>b.kind===kind).map(b=>{
      const done=Object.keys(ZS.data.progress).filter(id=>id.startsWith('pr-'+b.id+'-')&&ZS.data.progress[id].s).length;
      return '<article class="card p-book"><div class="p-book-type">'+(b.kind==='matching'?'连线 / 填序号':b.kind==='daily'?'真题 / 材料分析':'选择题 / 批注')+'</div><h3 title="'+esc(b.title)+'">'+esc(shortTitle[b.id]||b.title)+'</h3><div class="p-book-meta"><span>'+b.count+(b.kind==='matching'?' 组练习':' 道练习')+'</span><span>'+b.pages+' 页原图</span></div><div class="p-book-progress"><span>已练 '+Math.min(done,b.count)+' / '+b.count+'</span><div class="bar"><i style="width:'+Math.min(100,done/b.count*100)+'%"></i></div></div><div class="p-book-actions"><a class="btn main" href="#/sprint/practice/'+b.id+'">进入练习</a><a class="p-book-read" href="#/sprint/practice/'+b.id+'/read/1">'+(b.kind==='notes'?'浏览笔记':'浏览原页')+' →</a></div></article>';
    }).join('')+'</div></section>').join('')+'<p class="sprint-footnote">练习中保留错题、收藏、作答次数与资料对照；原 PDF 在原页浏览内打开。</p></div>');
  }
  function list(id,c){
    const b=book(id),d=books.get(id),state=listStates.get(id)||{chapter:'',filter:'all',query:'',page:1};listStates.set(id,state);
    c.shell('<div class="sprint-page"><a class="sprint-back" href="#/sprint/practice">‹ 全部资料</a><div class="hero sprint-hero"><span class="sprint-eyebrow">'+(b.kind==='notes'?'逐题笔记':b.kind==='matching'?'连线练习':'每日真题')+'</span><h1>'+esc(shortTitle[id]||b.title)+'</h1><p>'+b.count+' 道练习 · '+b.pages+' 页原图</p><a class="sprint-hero-link" href="#/sprint/practice/'+id+'/read/1">'+(b.kind==='notes'?'浏览原书批注与对比表':'浏览原文件')+' →</a></div><div class="sprint-filter card p-filters"><label>模块与章节<select id="pChapter"><option value="">全部章节</option>'+b.chapters.map(ch=>'<option value="'+esc(ch.key)+'">'+esc(ch.title)+' · '+ch.count+'题</option>').join('')+'</select></label><label>学习记录<select id="pFilter"><option value="all">全部题目</option><option value="wrong">错题</option><option value="star">收藏</option><option value="undone">未做</option></select></label><label class="p-filter-search">搜索题目<input id="pQuery" type="search" placeholder="题干、选项或连线内容"></label><div class="p-filter-note">原文件全文搜索请进入「浏览原文件」。</div></div><div id="pList"></div></div>');
    $('#pChapter').value=state.chapter;$('#pFilter').value=state.filter;$('#pQuery').value=state.query;
    const update=(reset=true)=>{
      state.chapter=$('#pChapter').value;state.filter=$('#pFilter').value;state.query=$('#pQuery').value.trim();if(reset)state.page=1;
      const ch=state.chapter,f=state.filter,t=state.query;
      const qs=d.questions.filter(q=>(!ch||q.module+' · '+q.chapter===ch)&&(!t||(q.stem+' '+Object.values(q.options).join(' ')+(q.left||[]).map(i=>i.text).join(' ')+(q.right||[]).map(i=>i.text).join(' ')).includes(t))&&(f==='wrong'?c.isWrongNow(q.id):f==='star'?c.flag(q.id,'star'):f==='undone'?!c.isDone(q.id):true));
      listIds=qs.map(q=>q.id);const size=20,pages=Math.max(1,Math.ceil(qs.length/size));state.page=Math.min(pages,state.page);const start=(state.page-1)*size,visible=qs.slice(start,start+size);let group='';
      const pager=qs.length>size?'<div class="sprint-pager"><button class="btn" id="pPrevPage" '+(state.page<=1?'disabled':'')+'>上一页</button><span>'+state.page+' / '+pages+' 页</span><button class="btn" id="pNextPage" '+(state.page>=pages?'disabled':'')+'>下一页</button></div>':'';
      $('#pList').innerHTML='<div class="sprint-result-count">'+qs.length+' 道练习'+(qs.length?' · 显示 '+(start+1)+'–'+(start+visible.length):'')+'</div>'+visible.map(q=>{
        const chapter=q.module+' · '+q.chapter,heading=chapter!==group?'<h2 class="p-list-chapter">'+esc(chapter)+'</h2>':'';group=chapter;
        const snippet=q.type==='matching'?(q.left||[]).slice(0,2).map(i=>i.text).join('；'):q.stem;
        return heading+'<button class="card p-qrow" onclick="ZS_GO(\'q/'+q.id+'\')"><span class="p-row-number">'+String(q.no).padStart(2,'0')+'</span><span class="p-row-content"><b>'+esc(q.section)+(q.originalNo?' · 原题 '+q.originalNo:'')+'</b><span class="p-row-snippet">'+esc(snippet)+'</span><small>'+esc(badge(q,c))+'</small></span><span class="p-row-arrow" aria-hidden="true">›</span></button>';
      }).join('')+pager+(qs.length?'':'<div class="empty">没有符合条件的题目，试试其他筛选条件。</div>');
      if($('#pPrevPage'))$('#pPrevPage').onclick=()=>{state.page--;update(false);$('#pList').scrollIntoView({block:'start',behavior:'smooth'});};
      if($('#pNextPage'))$('#pNextPage').onclick=()=>{state.page++;update(false);$('#pList').scrollIntoView({block:'start',behavior:'smooth'});};
    };
    ['pChapter','pFilter'].forEach(id=>$('#'+id).onchange=()=>update());$('#pQuery').oninput=()=>update();update(false);
  }
  function reader(id,n,c){const b=book(id),d=books.get(id);n=Math.max(1,Math.min(b.pages,n));const p=d.pages[n-1];c.shell('<div class="p-toolbar" id="pToolbar"><div class="acts"><button class="btn" onclick="ZS_GO(\'sprint/practice/'+id+'\')">题目目录</button><button class="btn" id="pCollapse">收回工具栏</button></div><div id="pTools"><b>'+esc(b.title)+'</b><div class="acts"><button class="btn" '+(n===1?'disabled':'')+' onclick="ZS_GO(\'sprint/practice/'+id+'/read/'+(n-1)+'\')">上一页</button><label>页码 <input type="number" id="pPage" min="1" max="'+b.pages+'" value="'+n+'"></label><span>/ '+b.pages+'</span><button class="btn" '+(n===b.pages?'disabled':'')+' onclick="ZS_GO(\'sprint/practice/'+id+'/read/'+(n+1)+'\')">下一页</button><select id="pReadChapter"><option value="">定位章节</option>'+b.chapters.map(ch=>'<option value="'+ch.firstPage+'">'+esc(ch.title)+'</option>').join('')+'</select></div><input id="pBookSearch" type="search" placeholder="在此原文件全文中查找（类似 PDF 搜索）"><div id="pSearchResults"></div></div></div><div class="tiny muted">原书浏览会显示着色答案与批注；练习入口在题目目录。</div><div class="pgwrap p-page" data-anno="_lec|p-'+id+'-'+n+'"><img src="'+src(id,n)+'" alt="'+esc(b.title)+' P'+n+'" data-label="'+esc(b.title)+' P'+n+'" onload="ZS_ANNOSYNC()" onclick="ZS_ZOOM(this)"><button class="annobtn" onclick="ZS_ANNO(\'_lec\',\'p-'+id+'-'+n+'\')">✍️</button></div><div class="acts">'+pdf(id,n)+'<button class="btn" onclick="ZS_ZOOMSRC(\''+src(id,n)+'\')">放大原图</button></div><details class="card pad"><summary>原页文字（完整布局请看原图）</summary><div class="txt">'+esc(p.text)+'</div></details>');fitBar($('#pToolbar'));$('#pCollapse').onclick=()=>{const el=$('#pTools');el.hidden=!el.hidden;$('#pCollapse').textContent=el.hidden?'展开工具栏':'收回工具栏';};$('#pPage').onchange=e=>{const v=Number(e.target.value);if(Number.isInteger(v)&&v>=1&&v<=b.pages)ZS_GO('sprint/practice/'+id+'/read/'+v);};$('#pReadChapter').onchange=e=>{if(e.target.value)ZS_GO('sprint/practice/'+id+'/read/'+e.target.value);};$('#pBookSearch').oninput=e=>{const t=e.target.value.trim(),hits=t?d.pages.filter(p=>p.text.includes(t)):[];$('#pSearchResults').innerHTML=(t?'<div class="tiny">'+hits.length+' 页命中</div>':'')+hits.map(p=>{const at=p.text.indexOf(t);return '<button class="btn p-search-hit" onclick="ZS_GO(\'sprint/practice/'+id+'/read/'+p.page+'\')">P'+p.page+' · '+esc(p.text.slice(Math.max(0,at-20),at+80))+'</button>';}).join('');};ANNO.renderScope();}
  function decode(p){try{const s=p?.sel?.[0]||'';return s.startsWith('match:')?JSON.parse(s.slice(6)):{};}catch(e){return {};}}
  function parsed(v){const cir='①②③④⑤⑥⑦⑧⑨⑩';v=String(v).replace(/[①-⑩]/g,x=>String(cir.indexOf(x)+1));if(!/^[\d\s,，、;；]*$/.test(v))return null;return Array.from(new Set(v.split(/[\s,，、;；]+/).filter(Boolean).map(x=>String(Number(x))))).sort((a,b)=>Number(a)-Number(b));}
  const equal=(a,b)=>JSON.stringify([...(a||[])].sort())===JSON.stringify([...(b||[])].sort());
  function renderQuestion(q,c){const id=q.id,p=c.P(id),answered=!!p?.s&&!c.S['redo_'+id],revealed=answered||!!c.S['rev_'+id];const stored=ZS.data.edit[id]||{};let pairs=answered?decode(p):clone(stored.practiceMatch||{}),text=answered?(p.sel?.[0]||'').replace(/^written:/,''):stored.practiceText||'',active=null,mode=localStorage.getItem('zz720.practiceMode')||'line';
    const matching=q.type==='matching';c.shell('<div class="card" style="margin-top:12px"><div class="qhd"><button class="iconbtn" onclick="ZS_GO(\'sprint/practice/'+q.bookId+'\')">☰</button><span class="idx">'+esc(q.module+' · '+q.chapter)+'</span><span class="chip">'+esc(q.section)+'</span><span class="sp"></span><button class="iconbtn '+(c.flag(id,'star')?'on':'')+'" onclick="ZS_FLAG(\''+id+'\',\'star\')">★</button></div><div class="qbody"><p class="tiny muted">'+esc(book(q.bookId).title)+'</p><div class="stem" id="qbox" data-anno="'+id+'|q-txt">'+esc(q.stem)+'</div>'+(matching?'<div class="acts"><button class="btn" id="pLineMode">连线</button><button class="btn" id="pNumberMode">填序号</button></div><p class="tiny muted">'+(q.multiMatch?'本题有一项对应多个序号，用逗号分隔；右侧内容可重复对应。':'点击左项后点击右项，或从左拖到右；再次连接可取消。右项按原书允许重复对应。')+'</p><div class="p-match" id="pBoard"><svg id="pLines" aria-hidden="true"></svg><div class="p-left">'+q.left.map(i=>'<button class="p-item" data-left="'+i.key+'"><b>'+esc(i.originalLabel)+'</b> '+esc(i.text)+'</button>').join('')+'</div><div class="p-right">'+q.right.map(i=>'<button class="p-item" data-right="'+i.key+'"><b>'+esc(i.key)+(i.originalLabel!==i.key?'（原 '+esc(i.originalLabel)+'）':'')+'</b> '+esc(i.text)+'</button>').join('')+'</div></div><div id="pNumberChoices" class="card pad">'+q.right.map(i=>'<p><b>'+esc(i.key)+'（原 '+esc(i.originalLabel)+'）</b> '+esc(i.text)+'</p>').join('')+'</div><div id="pNumbers">'+q.left.map(i=>'<label class="p-number"><span><b>'+esc(i.originalLabel)+'</b> '+esc(i.text)+'</span><input data-number="'+i.key+'" inputmode="numeric" aria-label="'+esc(i.originalLabel)+'对应序号" placeholder="'+(q.multiMatch?'例如 1,3':'填写序号')+'"></label>').join('')+'</div><div class="tiny" id="pPairs"></div>':'<label class="p-written">我的作答<textarea id="pWriting" rows="10" placeholder="按原题小问分别作答，展开参考答案后自行评估。"></textarea></label>')+'<div id="pControls" class="acts"></div><div id="pResult"></div></div></div>'+(revealed?'<details class="card pad" open><summary>原书答案 / 解析截图 + 文字</summary><div class="pages">'+questionPages(q)+'</div>'+q.analysis.map(a=>'<h3>'+esc(a.k)+'</h3><div class="txt">'+esc(a.t)+'</div>').join('')+'</details><div class="acc" id="accL"><div class="hd" onclick="ZS_ACC(this)">知识清单 / 速成班讲义 / 背诵手册对照<span class="arw">›</span></div><div class="bd"><p class="tiny muted">相同原文片段定位，请结合语境核对；未匹配的资料会说明没找到。</p><div class="tabs"><span class="tab on" onclick="ZS_TAB(this,\'k\')">知识清单</span><span class="tab" onclick="ZS_TAB(this,\'s\')">速成班讲义</span><span class="tab" onclick="ZS_TAB(this,\'m\')">背诵手册</span></div><div id="lectK" class="lectbox"></div><div id="lectS" class="lectbox" style="display:none"></div><div id="lectM" class="lectbox" style="display:none"></div></div></div><div id="noteSection"></div>':'<div class="card pad tiny muted">提交或展开参考答案后显示解析与资料对照。</div>'));
    c.showQNav(true,c.qIndexOf(id));currentEdit=id;ZS.beginEdit('edit',id,['practiceMatch','practiceText']);
    const save=()=>{const e=ZS.data.edit[id]=ZS.data.edit[id]||{};if(matching)e.practiceMatch=clone(pairs);else e.practiceText=text;e.ts=Date.now();ZS.save();};
    const again=()=>c.renderQuestion(id);
    const reveal=()=>{save();c.S['rev_'+id]=true;again();};
    const controls=$('#pControls'),result=$('#pResult');
    if(!revealed){controls.innerHTML='<button class="btn main" id="pSubmit">'+(matching?'提交答案':'展开参考答案')+'</button>'+(matching?'<button class="btn" id="pReveal">直接看答案</button><button class="btn" id="pClear">清除配对</button>':'');}
    else{controls.innerHTML=(!matching&&!answered?'<button class="btn main" id="pMastered">自评：已掌握</button><button class="btn" id="pReview">自评：仍需复习</button>':'')+'<button class="btn" onclick="ZS_REDO(\''+id+'\')">重做本题</button><button class="btn" onclick="ZS_ANNO(\''+id+'\',\'q-txt\')">✍️ 题目上做笔记</button>';if(answered)result.innerHTML='<div class="res '+(p.s==='right'?'ok':'bad')+'">'+(matching?(p.s==='right'?'✔ 全部配对正确':'✘ 有配对需要订正'):'自评：'+(p.s==='right'?'已掌握':'仍需复习'))+'</div><p class="tiny muted">已做 '+(p.tries||1)+' 次'+(matching?'，答对 '+(p.rights||0)+' 次':'（材料题由本人评估）')+'</p>';else result.textContent=matching?'直接看答案，不计入做题次数。':'材料分析不自动判分，请对照原书参考答案后自评。';}
    if(matching){
      const board=$('#pBoard'),svg=$('#pLines'),leftEls=[...board.querySelectorAll('[data-left]')],rightEls=[...board.querySelectorAll('[data-right]')],inputs=[...document.querySelectorAll('[data-number]')];
      const draw=(drag=null)=>{if(!board.isConnected||mode!=='line')return;const r=board.getBoundingClientRect();svg.setAttribute('viewBox','0 0 '+Math.max(1,r.width)+' '+Math.max(1,r.height));svg.innerHTML='';const line=(a,b,color)=>{const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d','M '+a.x+' '+a.y+' C '+(a.x+24)+' '+a.y+','+(b.x-24)+' '+b.y+','+b.x+' '+b.y);path.setAttribute('stroke',color);svg.appendChild(path);};leftEls.forEach(el=>{const k=el.dataset.left,a=el.getBoundingClientRect(),from={x:a.right-r.left,y:a.top+a.height/2-r.top};(pairs[k]||[]).forEach(v=>{const right=rightEls.find(e=>e.dataset.right===v);if(!right)return;const b=right.getBoundingClientRect();line(from,{x:b.left-r.left,y:b.top+b.height/2-r.top},revealed?(q.matchMap[k].includes(v)?'var(--teal)':'var(--bad)'):'var(--teal)');});if(drag&&active===k)line(from,{x:drag.x-r.left,y:drag.y-r.top},'var(--ink3)');});};
      const paint=()=>{inputs.forEach(e=>{if(document.activeElement!==e)e.value=(pairs[e.dataset.number]||[]).join(',');e.disabled=revealed;});leftEls.forEach(e=>{e.classList.toggle('active',active===e.dataset.left);e.disabled=revealed;});rightEls.forEach(e=>e.disabled=revealed);$('#pPairs').innerHTML=q.left.map(i=>{const yours=pairs[i.key]||[],right=q.matchMap[i.key];return '<span class="p-pair '+(revealed?(equal(yours,right)?'good':'bad'):'')+'">'+esc(i.originalLabel)+' → '+esc(yours.join(',')||'未选')+(revealed?' · 正确 '+esc(right.join(',')):'')+'</span>';}).join('');draw();};
      const setMode=v=>{mode=v;localStorage.setItem('zz720.practiceMode',v);board.hidden=v!=='line';$('#pNumbers').hidden=v!=='number';$('#pNumberChoices').hidden=v!=='number';$('#pLineMode').classList.toggle('main',v==='line');$('#pNumberMode').classList.toggle('main',v==='number');paint();};
      const connect=v=>{if(revealed||!active)return;const old=pairs[active]||[];pairs[active]=q.multiMatch?(old.includes(v)?old.filter(x=>x!==v):old.concat(v)):old.includes(v)?[]:[v];save();paint();};
      leftEls.forEach(el=>{el.onclick=()=>{if(!revealed){active=el.dataset.left;paint();}};el.onpointerdown=e=>{if(revealed)return;active=el.dataset.left;board.setPointerCapture?.(e.pointerId);e.preventDefault();paint();};});rightEls.forEach(el=>el.onclick=()=>connect(el.dataset.right));board.onpointermove=e=>{if(board.hasPointerCapture?.(e.pointerId))draw({x:e.clientX,y:e.clientY});};board.onpointerup=e=>{if(!board.hasPointerCapture?.(e.pointerId))return;board.releasePointerCapture?.(e.pointerId);const hit=rightEls.find(el=>{const r=el.getBoundingClientRect();return e.clientX>=r.left&&e.clientX<=r.right&&e.clientY>=r.top&&e.clientY<=r.bottom;});if(hit)connect(hit.dataset.right);else paint();};board.onpointercancel=e=>{board.releasePointerCapture?.(e.pointerId);paint();};
      inputs.forEach(e=>e.oninput=()=>{const v=parsed(e.value);if(v!==null){pairs[e.dataset.number]=v;save();paint();}});$('#pLineMode').onclick=()=>setMode('line');$('#pNumberMode').onclick=()=>setMode('number');setMode(mode);if(window.ResizeObserver){observer=new ResizeObserver(()=>draw());observer.observe(board);}
      if(!revealed){$('#pSubmit').onclick=()=>{if(mode==='number'&&inputs.some(e=>parsed(e.value)===null))return ZS.toast('只填写序号，多个序号用逗号分隔');if(q.left.some(i=>!(pairs[i.key]||[]).length))return ZS.toast('请完成每一项配对');if(q.left.some(i=>(pairs[i.key]||[]).some(v=>!q.right.some(r=>r.key===v))||(!q.multiMatch&&pairs[i.key].length!==1)))return ZS.toast('请核对序号范围与每项数量');save();c.setProg(id,q.left.every(i=>equal(pairs[i.key],q.matchMap[i.key])),false,['match:'+JSON.stringify(pairs)]);again();};$('#pReveal').onclick=reveal;$('#pClear').onclick=()=>{pairs={};active=null;inputs.forEach(e=>e.value='');save();paint();};}
    }else{const el=$('#pWriting');el.value=text;el.readOnly=answered;el.oninput=()=>{text=el.value;save();};if(!revealed)$('#pSubmit').onclick=reveal;if(revealed&&!answered){const assess=right=>{text=el.value;if(!text.trim())return ZS.toast('先填写自己的作答，再进行自评');save();c.setProg(id,right,false,['written:'+text]);again();};$('#pMastered').onclick=()=>assess(true);$('#pReview').onclick=()=>assess(false);}}
    if(revealed){c.needLect().then(()=>{if(c.S.cur===q)c.paintLect(q);});c.renderNote(id);ANNO.renderScope();}
  }
  return {load,render,needBook,ensureQuestion,pool,leave,reset,questionPages,questionPdf,renderQuestion,parsed,decode,equal,get index(){return index;},get books(){return books;}};
})();
