import {Window} from 'happy-dom';import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';
process.chdir(path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..')); import assert from 'node:assert/strict';
const w=new Window({url:'http://localhost/',settings:{enableJavaScriptEvaluation:true,disableCSSFileLoading:true,disableJavaScriptFileLoading:true}});w.localStorage.setItem('zz720.v1.cfg',JSON.stringify({gate:'0',auto:false}));w.document.write(fs.readFileSync('index.html','utf8').replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''));w.fetch=async u=>new Response(String(u).startsWith('https://aokid666.github.io/zz-manual-')?JSON.stringify({lines:[]}):fs.readFileSync(path.join('.',String(u).split('?')[0])),{status:200});let scrollY=0;Object.defineProperty(w,'scrollY',{get:()=>scrollY});w.scrollTo=(x,y)=>{scrollY=y;};w.HTMLElement.prototype.scrollIntoView=()=>{};w.HTMLElement.prototype.setPointerCapture=()=>{};w.ResizeObserver=class{observe(){}disconnect(){}};w.HTMLCanvasElement.prototype.getContext=()=>new Proxy({},{get:(_,k)=>k==='measureText'?()=>({width:8}):()=>{}});
for(const n of ['store','annotate','manual','practice','app'])w.eval(fs.readFileSync('js/'+n+'.js','utf8'));w.document.dispatchEvent(new w.Event('DOMContentLoaded'));
const $=s=>w.document.querySelector(s),wait=async(fn)=>{for(let i=0;i<400;i++){if(fn())return;await new Promise(r=>setTimeout(r,10));}throw Error('Timeout: '+fn);};const go=async h=>{w.ZS_GO(h);await new Promise(r=>setTimeout(r,20));};
await wait(()=>$('#view').textContent.includes('冲刺板块'));assert($('#view').textContent.includes('1389'));
await go('sprint');assert.equal(w.document.querySelectorAll('.sprint-entry').length,4);assert.equal(w.document.querySelectorAll('.sprint-entry-mark').length,4);assert.equal(w.document.querySelectorAll('.sprint-overview>div').length,3);assert.equal(w.document.querySelectorAll('.m-topics').length,0);
const snapshot=(name)=>{if(!process.env.SPRINT_PREVIEW)return;const out=path.resolve('../practice-work/preview');fs.mkdirSync(out,{recursive:true});let html=w.document.documentElement.outerHTML.replace(/href="css\//g,'href="/manual-source/css/');fs.writeFileSync(path.join(out,name+'.html'),'<!doctype html>'+html);};snapshot('home');w.document.documentElement.setAttribute('data-theme','dark');snapshot('home-dark');w.document.documentElement.setAttribute('data-theme','light');
await go('sprint/topics');assert.equal(w.document.querySelectorAll('.m-topics .btn').length,123);assert.equal(w.document.querySelectorAll('.sprint-topic-group[open]').length,1);$('#mTopicSearch').value='矛盾';$('#mTopicSearch').dispatchEvent(new w.Event('input'));assert(w.document.querySelectorAll('.m-topics .btn').length>0);assert(w.document.querySelectorAll('.m-topics .btn').length<123);
await go('sprint/questions');assert.equal(w.document.querySelectorAll('.m-qrow').length,20);assert($('#mQuestionList').textContent.includes('193'));$('#mNextList').click();assert(w.document.querySelector('.m-qrow').getAttribute('onclick').includes('ms021'));w.scrollTo(0,740);await go('q/ms021');assert($('#opts'));w.ZS_BACK();await wait(()=>$('#mQuestionList'));await new Promise(r=>setTimeout(r,30));assert.equal(w.scrollY,740);assert(w.document.querySelector('.m-qrow').getAttribute('onclick').includes('ms021'));
await go('sprint/practice');await wait(()=>w.document.querySelectorAll('.p-book').length===10);assert.equal(w.document.querySelectorAll('.p-collection-group').length,3);snapshot('books');w.document.documentElement.setAttribute('data-theme','dark');snapshot('books-dark');w.document.documentElement.setAttribute('data-theme','light');assert.equal(w.PRACTICE.index.total,1389);
await go('sprint/practice/cf-upper');await wait(()=>$('.p-qrow'));assert.equal(w.document.querySelectorAll('.p-qrow').length,20);assert($('#pList').textContent.includes('562'));$('#pNextPage').click();assert.equal($('.p-row-number').textContent,'21');await go('q/pr-cf-upper-choice-0021');await go('sprint/practice/cf-upper');await wait(()=>$('#pNextPage'));assert.equal($('.p-row-number').textContent,'21');$('#pQuery').value='没有这个知识点987654';$('#pQuery').dispatchEvent(new w.Event('input'));assert.equal(w.document.querySelectorAll('.p-qrow').length,0);$('#pQuery').value='';$('#pQuery').dispatchEvent(new w.Event('input'));assert.equal($('.p-row-number').textContent,'01');snapshot('questions');const cf=w.PRACTICE.books.get('cf-upper').questions[0];await go('q/'+cf.id);assert(!$('#aPages'));assert.equal(w.document.querySelectorAll('#opts .opt').length,4);w.ZS_SEL(cf.id,cf.answer);w.ZS_SUBMIT(cf.id);await wait(()=>$('#aPages img'));assert.equal(w.ZS.data.progress[cf.id].sel.join(''),cf.answer);assert($('#aPages img').src.includes('zz-sprint-practice-2027'));assert($('#lectM'));w.ZS_QNAV(1);await wait(()=>$('.idx').textContent.includes('原题 2'));
await go('q/pr-ethics-match-matching-0001');await wait(()=>$('#pBoard'));const m=w.PRACTICE.books.get('ethics-match').questions[0];assert(!$('#aPages'));assert(!$('#lectK'));
$('#pLineMode').click();const first=m.left[0].key,right=m.matchMap[first][0];$('[data-left="'+first+'"]').click();$('[data-right="'+right+'"]').click();assert($('#pPairs').textContent.includes(first+' → '+right));assert.equal($('#pLines').children.length,1);$('#pNumberMode').click();assert.equal($('[data-number="'+first+'"]').value,right);assert($('#pBoard').hidden);assert(!$('#pNumberChoices').hidden);assert($('#pNumberChoices').textContent.includes(m.right[0].text));
for(const i of m.left){const el=$('[data-number="'+i.key+'"]');el.value=m.matchMap[i.key].join(',');el.dispatchEvent(new w.Event('input'));}$('#pSubmit').click();assert.equal(w.ZS.data.progress[m.id].s,'right');assert.equal(w.ZS.data.progress[m.id].tries,1);assert.deepEqual(JSON.parse(w.ZS.data.progress[m.id].sel[0].slice(6)),m.matchMap);assert(!$('#pSubmit'));$('#pLineMode').click();$('#pNumberMode').click();assert.equal(w.ZS.data.progress[m.id].tries,1);await wait(()=>$('#lectK').textContent.trim());
await go('sprint/practice/ethics-match');await wait(()=>$('#pFilter'));$('#pFilter').value='star';$('#pFilter').dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('.p-qrow').length,0);await go('q/'+m.id);await wait(()=>$('#pPairs'));assert($('#pPairs').textContent.includes(first+' → '+right));w.ZS_FLAG(m.id,'star');assert.equal(w.ZS.data.flags[m.id].star,true);
w.ZS_REDO(m.id);await wait(()=>$('#modal .mbox')||$('#modal').textContent.includes('确定'));const confirm=[...$('#modal').querySelectorAll('button')].find(b=>/确定|确认/.test(b.textContent));assert(confirm);confirm.click();await wait(()=>$('#pSubmit'));assert([...w.document.querySelectorAll('[data-number]')].every(el=>el.value===''));assert.equal(w.ZS.data.progress[m.id].tries,1);
await go('sprint/practice/leg-marx');await wait(()=>$('#pList'));const many=w.PRACTICE.books.get('leg-marx').questions.find(q=>q.multiMatch);await go('q/'+many.id);await wait(()=>$('#pNumbers'));$('#pNumberMode').click();for(const i of many.left){const el=$('[data-number="'+i.key+'"]');el.value=many.matchMap[i.key].join(',');el.dispatchEvent(new w.Event('input'));}$('#pSubmit').click();assert.equal(w.ZS.data.progress[many.id].s,'right');
await go('sprint/practice/xu-daily');await wait(()=>$('#pList'));const written=w.PRACTICE.books.get('xu-daily').questions.find(q=>q.type==='written');await go('q/'+written.id);await wait(()=>$('#pWriting'));$('#pWriting').value='我的分析：从实践与认识的关系作答。';$('#pWriting').dispatchEvent(new w.Event('input'));$('#pSubmit').click();await wait(()=>$('#pReview'));assert(!w.ZS.data.progress[written.id]);$('#pReview').click();assert.equal(w.ZS.data.progress[written.id].s,'wrong');assert(w.ZS.data.progress[written.id].sel[0].includes('我的分析'));
await go('sprint/practice/cf-upper/read/11');await wait(()=>$('#pBookSearch'));$('#pBookSearch').value='矛盾';$('#pBookSearch').dispatchEvent(new w.Event('input'));assert(w.document.querySelectorAll('.p-search-hit').length>0);$('#pCollapse').click();assert($('#pTools').hidden);$('#pCollapse').click();assert(!$('#pTools').hidden);assert($('.p-page img').src.endsWith('/cf-upper/011.png'));
// Back retains filtered source lists and scroll; continuous navigation follows that pool.
await go('sprint/points');assert($('.m-study-grid'));snapshot('points');w.document.documentElement.setAttribute('data-theme','dark');snapshot('points-dark');w.document.documentElement.setAttribute('data-theme','light');$('#mKind').value='干扰项';$('#mKind').dispatchEvent(new w.Event('change'));$('#mModule').value=w.MANUAL.study.blocks.find(b=>b.kind==='干扰项').module;$('#mModule').dispatchEvent(new w.Event('change'));
const blocks=w.MANUAL.study.blocks.filter(b=>b.kind==='干扰项'&&b.module===$('#mModule').value);assert(blocks.length>2);w.scrollTo(0,1280);await go('sprint/block/'+blocks[0].id);assert($('#mPrevBlock').disabled);assert(!$('#mNextBlock').disabled);assert($('.m-block-nav').textContent.includes('1 / '+blocks.length));$('#mCollapse').click();assert($('#mTools').hidden);assert(!$('.m-block-nav').hidden);$('#mNextBlock').click();await wait(()=>$('.m-block-nav').textContent.includes('2 / '+blocks.length));assert($('.m-block-nav').textContent.includes('2 / '+blocks.length));$('#mPrevBlock').click();await wait(()=>$('.m-block-nav').textContent.includes('1 / '+blocks.length));w.ZS_BACK();await wait(()=>$('#mResults'));await new Promise(r=>setTimeout(r,30));assert.equal($('#mKind').value,'干扰项');assert.equal(w.document.querySelectorAll('.m-study-card').length,blocks.length);assert.equal(w.scrollY,1280);
// Native browser Back, async book loading and same-route question redraw retain position.
await go('sprint/practice/cf-upper');await wait(()=>$('#pQuery'));w.scrollTo(0,960);await go('q/pr-cf-upper-choice-0001');w.history.back();await wait(()=>$('#pQuery'));await new Promise(r=>setTimeout(r,30));assert.equal(w.scrollY,960);w.dispatchEvent(new w.Event('wheel'));w.scrollTo(0,1110);$('#view').dispatchEvent(new w.Event('load'));assert.equal(w.scrollY,1110);
await go('q/pr-cf-upper-choice-0001');w.scrollTo(0,420);w.ZS_FLAG(cf.id,'star');await new Promise(r=>setTimeout(r,30));assert.equal(w.scrollY,420);
// Recommended manual clozes switch between one core fact, three exam facts and a bounded review set.
await go('sprint/page/u011');await wait(()=>$('#manualSheet'));assert.equal(w.document.querySelectorAll('.m-mask').length,3);assert.equal(w.document.querySelectorAll('.m-cue').length,3);assert($('#mClozeGuide').textContent.includes('题库同源'));w.document.querySelectorAll('.m-cue')[0].click();assert($('#mClozeGuide').textContent.includes('答案：客观实在性'));w.document.querySelectorAll('.m-mask')[1].click();assert([...w.document.querySelectorAll('.m-mask')].some(x=>x.getAttribute('aria-label').includes('不以人的意志为转移')));$('#mPlan').value='core';$('#mPlan').dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('.m-mask').length,1);$('#mPlan').value='more';$('#mPlan').dispatchEvent(new w.Event('change'));assert.equal(w.document.querySelectorAll('.m-mask').length,4);assert($('#mModeHint').textContent.includes('题库同源'));
await go('q/q002');w.ZS_REVEAL('q002');await wait(()=>$('#lectM'));assert($('#opts'));assert(!$('#pBoard'));
// Every source-bound judgment has eagerly loaded original evidence in the answer panel.
for(const q of w.MANUAL.judgements){const holder=w.document.createElement('div');holder.innerHTML=w.MANUAL.questionPages(q,'key');const imgs=holder.querySelectorAll('.m-evidence img');assert.equal(imgs.length,w.MANUAL.study.blocks.find(b=>b.id===q.blockId).refs.length,q.id);for(const img of imgs){assert(img.src.endsWith('.png'));assert.equal(img.loading,'eager');assert.equal(img.parentElement.dataset.tgt,'a-img');assert(parseFloat(img.parentElement.style.paddingTop)>0);assert(img.width>0&&img.height>0);}}
const judgement=w.MANUAL.judgements.find(q=>q.answer==='B');await go('q/'+judgement.id);assert(!$('#aPages'));w.ZS_SEL(judgement.id,'B');w.ZS_SUBMIT(judgement.id);await wait(()=>$('#aPages .m-evidence img'));assert.equal($('#aPages .m-evidence img').loading,'eager');assert($('#aPages').textContent.includes('查看完整原图'));snapshot('judgement-evidence');
w.ZS.load();assert.equal(w.ZS.data.progress[many.id].tries,1);assert.equal(JSON.stringify(w.PRACTICE.decode(w.ZS.data.progress[many.id])),JSON.stringify(many.matchMap));console.log('PASS: semantic manual cloze tiers and exact answers, back scroll, native Back, filtered source previous/next, collapsed controls, list pagination retained, user scrolling cancels restoration, 10 books, blind notes, original screenshot links, normal choice grading, lazy direct URLs/navigation, matching lines/number shared state, many-to-many, record persistence, redo counters, written self-assessment, reader search/collapse, original questions preserved.');await w.happyDOM.abort();await w.happyDOM.close();
